import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';

interface Step { icon: string; title: string; color: string; content: string; deeper: string }

const SCHOOL_STEPS: Step[] = [
  { icon: '🚀', title: 'Your AI Teaching Co-Pilot', color: '#1B3A6B', content: 'LEAP (Learning Execution and Acceleration Platform) transforms how you plan, deliver, and adapt your teaching — powered by AI, guided by you. It\'s not just another LMS. It\'s an intelligent platform that understands the knowledge architecture of your subject and helps you deliver every session effectively.', deeper: 'The AI analyzes your syllabus, creates a complete lesson plan for every session, generates Socratic teaching scripts, builds quizzes with 10+ questions per lesson, and continuously adapts based on student performance. You remain in full control — review, modify, and approve everything before it reaches students.\n\nWhat this means for you: You go from "I have a syllabus" to "I have 30 fully planned sessions with lesson plans, teaching scripts, and quizzes" — in minutes, not weeks.' },
  { icon: '📄', title: 'Upload Your Syllabus', color: '#2E75B6', content: 'Upload any syllabus (PDF, Word, or text) and the AI performs a 10-step deconstruction: Extract Concepts → Build Knowledge Graph → Define Gates → Map Bloom\'s Taxonomy → Reorder to Cognitive Sequence → Design Lessons → Generate Socratic Scripts → Create Questions → Build Visual Map → Define Outcomes.', deeper: 'You also set your timetable: how many sessions and how long each session is. The AI distributes lessons across your exact schedule.\n\nWhat this means for you: No more spending weekends building lesson plans. Upload once, and get a complete semester plan tailored to your schedule.' },
  { icon: '💡', title: 'Syllabus Best Practices', color: '#B45309', content: 'The quality of AI-generated content depends directly on the quality of your syllabus input. A well-structured syllabus with clear topic hierarchies, prerequisites, and learning objectives will produce dramatically better knowledge graphs, lesson plans, and quizzes.', deeper: 'DO: List topics with clear hierarchy (chapters → units → sub-topics). Include prerequisite info ("requires knowledge of fractions"). Mention learning objectives or outcomes. Include textbook chapter names for context. Specify which topics are foundational vs advanced.\n\nDON\'T: Upload just a list of page numbers. Use vague names like "Chapter 3" without describing the content. Skip prerequisite relationships between topics. Leave out the scope or depth expected for each topic.\n\nWhat this means for you: Spend 5 extra minutes structuring your syllabus input clearly, and the AI will generate content that requires almost no editing — saving you hours of review time.' },
  { icon: '🗺️', title: 'Knowledge Graph & Gates', color: '#1E7E34', content: 'Your subject is broken into Critical Gates — conceptual checkpoints that must be mastered before moving forward. Each gate contains sub-concepts, and gates have dependencies: "Gate 2 (HCF/LCM) requires Gate 1 (Numbers)" means students can\'t skip ahead.', deeper: 'Some gates can run in parallel because they don\'t depend on each other. The AI identifies these parallel tracks automatically. This prevents the "Swiss cheese" problem where students have scattered knowledge with hidden gaps.\n\nWhat this means for you: You can see at a glance which topics depend on which, and plan your teaching sequence with confidence.' },
  { icon: '🧠', title: 'DIKW Learning Progression', color: '#8B5CF6', content: 'Every course follows the DIKW framework: Data → Information → Knowledge → Wisdom. Early lessons focus on facts and definitions (Data). Mid lessons build understanding and application (Information → Knowledge). Late lessons develop judgment, critique, and original thinking (Wisdom). The AI builds this progression automatically into every lesson plan, Socratic script, and quiz.', deeper: 'DIKW maps to Bloom\'s Taxonomy:\n- Data = Remember (recall facts, definitions)\n- Information = Understand (explain meaning, interpret)\n- Knowledge = Apply + Analyze (solve problems, find patterns, compare)\n- Wisdom = Evaluate + Create (judge, critique, design, defend positions)\n\nThe platform automatically tags each lesson with its DIKW level. Socratic scripts adapt: Data lessons are teacher-led explanations; Wisdom lessons are student-led debates. Quiz distribution shifts: early quizzes emphasize recall; late quizzes emphasize evaluation and creation.\n\nThe Golden Rule: If AI can do it, don\'t spend class time on it. AI handles Data and Information. Your class time is for Knowledge and Wisdom — where human teaching matters most.\n\nWhat this means for you: The platform ensures your course naturally progresses from memorization to wisdom. You can see in the DIKW dashboard where each student sits — stuck at Data (memorizing) or reaching Wisdom (thinking independently).' },
  { icon: '📚', title: 'Session-Ready Lesson Plans', color: '#7C3AED', content: 'Every session gets a complete lesson plan: Learning Objective, Key Idea, Conceptual Breakthrough, real-world Examples, practice Exercises, and Bloom\'s Taxonomy levels. Lessons progress from Remember → Create across the course.', deeper: 'Each lesson is designed to build cognitive depth naturally. Early lessons focus on Remember and Understand, middle on Apply and Analyze, final on Evaluate and Create.\n\nWhat this means for you: Walk into every class knowing exactly what to teach, how to explain it, and what to assign.' },
  { icon: '💬', title: 'Socratic Teaching Scripts', color: '#B45309', content: 'Every lesson comes with a 4-stage guided discovery script: Hook (5 min) → Discovery (15 min) → Concept Build (12 min) → Application (8 min). Students discover ideas rather than being told them.', deeper: 'Every stage includes the exact question to ask, what students are likely to respond, and how to bridge to the next stage.\n\nWhat this means for you: You don\'t have to improvise in class. The script gives you a proven teaching structure for every lesson.' },
  { icon: '📝', title: 'Quiz Questions Per Lesson', color: '#DC2626', content: 'Every lesson has 10 carefully designed questions: 3 MCQ, 2 True/False, 2 Short Answer, 2 Open-ended, and 1 Create-level challenge. Each includes correct answers, rubrics, and common misconceptions.', deeper: 'Questions test real understanding, not just recall. The distractors are designed based on actual student misconceptions.\n\nWhat this means for you: Ready-made assessments for every session — no more writing questions from scratch.' },
  { icon: '✅', title: 'Review & Approve Everything', color: '#16A34A', content: 'After AI processing, you review each lesson as a complete unit: Plan + Socratic Script + Quiz. Accept or reject with one click. Nothing goes live without your explicit approval.', deeper: 'The review page groups lessons by gate. You see everything the AI generated in context.\n\nWhat this means for you: You\'re the expert. The AI drafts, you decide.' },
  { icon: '📊', title: 'Real-Time Analytics', color: '#2E75B6', content: 'Four analytics views: Course Overview, Session View, Student Performance (mastery heatmap, Bloom\'s radar), and AI Guide (adaptive suggestions).', deeper: 'The Course Overview shows gate status. Student tab shows a heatmap of every student\'s mastery across every gate, and dependency risk alerts.\n\nWhat this means for you: Data tells you exactly which students need attention, on which topics, and at which cognitive level.' },
  { icon: '🤖', title: 'AI Guide — Adaptive Suggestions', color: '#7C3AED', content: 'After each session, the AI analyzes performance and suggests changes: Topic Shifts, Socratic Updates, Quiz Adjustments, Remediation, Peer Teaching, Pace Changes, and Bloom Focus shifts.', deeper: 'Each suggestion shows the current plan vs. proposed change side-by-side. You accept, edit, or reject each suggestion.\n\nWhat this means for you: The AI watches performance 24/7 and tells you exactly what to adjust.' },
  { icon: '🔒', title: 'Privacy & Data Security', color: '#374151', content: 'Complete data segregation. Row-Level Security on every table. All API endpoints verify teacher ownership. Powered by Supabase with enterprise-grade PostgreSQL.', deeper: 'Your courses, students, analytics, and suggestions are completely private.\n\nWhat this means for you: Teach with confidence knowing your data is secure.' },
  { icon: '🎯', title: 'One Platform, Every Class Level', color: '#0891B2', content: 'LEAP automatically adapts its entire AI pipeline based on the class level — Primary (Class 1-5), Middle (Class 6-8), or Senior (Class 9-12). The same platform generates age-appropriate lesson plans, Socratic scripts, quiz questions, and analytics for a Class 3 English course and a Class 11 Economics course — with fundamentally different pedagogy for each.', deeper: 'For Primary (Class 1-5): Simple language (5-10 word sentences), story-based Socratic hooks, Bloom\'s ceiling at Apply, 3-option MCQs, fill-in-the-blank questions, 30-minute sessions. Examples from daily life — school, animals, family.\n\nFor Middle (Class 6-8): Discovery-oriented teaching, real-world problem hooks, Bloom\'s up to Analyze, graduated difficulty exercises, worked examples, 40-minute sessions. Mix of concrete and abstract examples.\n\nFor Senior (Class 9-12): Full Socratic dialogue with debate and case studies, complete Bloom\'s taxonomy including Evaluate and Create, essay and analytical questions, real Indian data and current affairs, 45-50 minute sessions.\n\nThe class level is set when creating a course. Every AI-generated artifact — from lesson titles to quiz distractors to chatbot tone — automatically adjusts. A teacher creating courses for different classes doesn\'t need to configure anything manually.\n\nWhat this means for you: Whether you teach Class 3 or Class 12, the platform speaks the right language for your students. No configuration needed — just set the class level and the AI handles the rest.' },
];

const COLLEGE_STEPS: Step[] = [
  { icon: '🎓', title: 'Multi-Course AI Platform', color: '#7C3AED', content: 'LEAP for higher education manages entire course programs — not just individual subjects. Upload syllabi for multiple courses, and the AI discovers how they connect: which topics in Linear Algebra are prerequisites for Machine Learning, which CS concepts feed into AI courses.', deeper: 'Unlike single-course platforms, LEAP understands that a student failing Matrix Operations in Math 201 will predictably struggle with Neural Networks in CS 301. The platform tracks these cross-course dependencies automatically.\n\nWhat this means for you: You see the complete picture of how your courses interconnect, and can intervene before bottlenecks cascade.' },
  { icon: '🗺️', title: 'Cross-Course Knowledge Graph', color: '#2E75B6', content: 'Each course has its own Knowledge Graph with Gates (conceptual checkpoints). But LEAP goes further — it connects gates ACROSS courses. "CS 301 Gate 2 (Regression) requires MATH 201 Gate 2 (Linear Transformations)" is a cross-course dependency that no single-course tool can see.', deeper: 'The Program View shows all your courses as swim lanes with gates as nodes. Within-course arrows show internal progression. Purple cross-course arrows show inter-disciplinary dependencies. You can hover over any gate to see what depends on it.\n\nWhat this means for you: You can instantly see which foundational topics in one course are blocking progress in another — and coordinate with other professors to address gaps.' },
  { icon: '📄', title: 'Upload Syllabi Per Course', color: '#1E7E34', content: 'Upload a syllabus for each course in your program (PDF, Word, or text). The AI deconstructs each into Gates, Lessons, Socratic Scripts, and Quizzes — then automatically identifies cross-course dependencies based on topic overlap and prerequisite chains.', deeper: 'For a 3-course CS program, you get: ~12 gates total, ~72 lessons with scripts, ~720 quiz questions, and 6+ cross-course dependency edges — all from 3 syllabus uploads.\n\nWhat this means for you: An entire semester\'s teaching material, across multiple courses, generated and interconnected in minutes.' },
  { icon: '💡', title: 'Syllabus Best Practices', color: '#B45309', content: 'The AI automatically detects cross-course dependencies by analyzing gate topics across your courses. For this to work well, your syllabi must be descriptive and use specific topic names — not vague chapter numbers.', deeper: 'DO: Use specific topic names ("Linear Regression", "Matrix Operations") not just "Topic 3". Include prerequisite knowledge clearly ("requires Calculus I concepts"). List learning outcomes that reference specific skills. Mention which concepts from other courses are needed.\n\nDON\'T: Upload just page numbers or chapter numbers without context. Use abbreviations the AI can\'t understand. Skip mentioning which topics depend on other courses.\n\nCROSS-COURSE TIP: When uploading a syllabus for an advanced course (like Machine Learning), explicitly mention prerequisites: "Requires Linear Algebra (vectors, matrices, eigenvalues) and Probability (distributions, Bayes theorem)." This helps the AI create accurate cross-course dependency edges.\n\nWhat this means for you: Well-structured syllabi produce accurate cross-course knowledge graphs, meaning the bottleneck detection and student analytics will correctly identify which students are stuck because of gaps in prerequisite courses.' },
  { icon: '📊', title: 'Bottleneck Detection', color: '#DC2626', content: 'LEAP\'s Bottleneck tab shows exactly where students are stuck across courses. "3 students blocked in CS 301 G2 because they lack MATH 201 G2 mastery" — this is the insight that\'s invisible when each course is managed separately.', deeper: 'The bottleneck analysis shows: which prerequisite gate is the blocker, which downstream gate is affected, how many students are impacted, and the severity. You can see cascade risk — if 5 students fail Probability in Math, they\'ll fail ML Foundations, then Regression, then Neural Networks.\n\nWhat this means for you: You can prioritize remediation in the prerequisite course to unblock progress across the entire program.' },
  { icon: '📚', title: 'Lesson Plans & Socratic Scripts', color: '#B45309', content: 'Every lesson across every course gets a complete plan: Learning Objective, Key Idea, Conceptual Breakthrough, Examples, Exercises. Socratic Scripts guide 4-stage discovery: Context Setting → Guided Exploration → Formalization → Application & Synthesis.', deeper: 'College-level scripts are different from K-12: they emphasize student-led exploration, peer discussion, and synthesis of ideas across topics. The Bloom\'s Taxonomy distribution shifts upward — more Analyze, Evaluate, and Create.\n\nWhat this means for you: Research-backed teaching scripts for every session, designed for higher education cognitive levels.' },
  { icon: '📈', title: 'Program-Level Analytics', color: '#7C3AED', content: 'See each student\'s performance across ALL your courses in a single view. The cross-course heatmap shows mastery per gate across CS 101, MATH 201, and CS 301 — revealing patterns like "strong coder but weak math" or "solid theory but can\'t apply."', deeper: 'The Students tab in the Program View shows overall mastery per student, broken down by course. Students flagged as at-risk in one course automatically get highlighted in dependent courses.\n\nWhat this means for you: One dashboard to understand each student holistically, not through the narrow lens of a single course.' },
  { icon: '🤖', title: 'AI Suggestions Across Courses', color: '#1B3A6B', content: 'AI generates suggestions that span courses: "Coordinate with Math department — 3 ML students need Linear Algebra remediation" or "Peer teaching: Priyanka (88% in CS) can help Vikram (40%) with Data Structures, which would unblock his ML progress."', deeper: 'Unlike single-course suggestions, cross-course recommendations identify root causes in prerequisite courses and suggest coordinated interventions. The AI considers the full dependency graph when making recommendations.\n\nWhat this means for you: Actionable, cross-departmental suggestions that actually address the root cause of student struggles.' },
  { icon: '🔒', title: 'Privacy & Security', color: '#374151', content: 'Complete data segregation. Each professor sees only their own courses and students. Row-Level Security on every table. Enterprise-grade PostgreSQL via Supabase.', deeper: 'Student data is isolated per course and per professor. Cross-course analytics only work for courses you teach or have explicit access to.\n\nWhat this means for you: Full privacy and security, even in a multi-course environment.' },
  { icon: '🎯', title: 'One Platform, Every Level', color: '#0891B2', content: 'LEAP adapts its entire AI pipeline based on class level. The same platform generates fundamentally different pedagogy for a foundation-year course (simple language, guided exercises, lower Bloom ceiling) versus a final-year seminar (case-study analysis, full Bloom spectrum, debate-oriented Socratic scripts). Set the level when creating a course — everything adapts automatically.', deeper: 'For foundation/introductory courses: Clear language with terms defined, discovery-oriented hooks, Bloom\'s up to Analyze, graduated difficulty, worked examples, 40-minute sessions.\n\nFor advanced/senior courses: Academic discipline-specific language, Socratic dialogues with debate and case studies, full Bloom\'s taxonomy including Evaluate and Create, essay and analytical questions, real-world data and current affairs, 50-minute sessions.\n\nThe AI adjusts lesson titles, example sources, question types, Socratic script tone, and even the chatbot\'s communication style. A single professor teaching both an intro and advanced course gets appropriately differentiated content without any extra configuration.\n\nWhat this means for you: Whether it\'s a first-year fundamentals course or a final-year research seminar, LEAP generates the right pedagogy for the level. No manual tuning needed.' },
];

const STUDENT_STEPS: Step[] = [
  { icon: '🚀', title: 'Your Personal Learning Platform', color: '#1B3A6B', content: 'LEAP adapts to how you learn. Every lesson has been carefully structured by AI and your teacher to help you build understanding step by step — from simple recall to creative problem-solving.', deeper: 'The platform tracks your mastery across every topic (called "Gates"). You can see exactly where you\'re strong and where you need more practice. The AI adapts questions based on your performance — if you\'re doing well, it challenges you more. If you\'re struggling, it provides more support.\n\nWhat this means for you: Learning that actually fits your pace and level.' },
  { icon: '📚', title: 'Lesson Materials', color: '#2E75B6', content: 'Each lesson has a complete plan: what you\'ll learn, the key idea, real-world examples, and exercises. You can review slides, listen to audio narration, or watch a narrated video — whatever works best for your learning style.', deeper: 'Lessons also include a Mind Map showing how all the concepts connect, and Flashcards for quick revision. Use the Lesson Chatbot to ask questions about anything you don\'t understand — it knows the lesson content and can explain things in simpler terms.\n\nWhat this means for you: Multiple ways to learn every concept — visual, audio, interactive. Pick what works for you.' },
  { icon: '📝', title: 'Interactive Quizzes', color: '#7C3AED', content: 'Every lesson has a quiz with 10 questions across different difficulty levels. Take the Interactive Quiz to test yourself — you get immediate feedback on each answer, see your score, and learn from your mistakes.', deeper: 'Questions range from simple recall (Remember) to creative challenges (Create). If you get something wrong, the quiz shows you the correct answer AND explains the common misconception that led you astray.\n\nWhat this means for you: Quizzes that actually help you learn, not just test you.' },
  { icon: '📊', title: 'Track Your Progress', color: '#16A34A', content: 'See your mastery across every topic gate. The progress page shows your Bloom cognitive profile — how well you do at remembering, understanding, applying, and analyzing concepts.', deeper: 'Your teacher can see this too, so they know exactly where to help you. The platform identifies your learning style (visual, logical, kinesthetic, etc.) and uses it to recommend the best study approach.\n\nWhat this means for you: You always know where you stand and what to focus on next.' },
  { icon: '🧠', title: 'Your DIKW Learning Journey', color: '#8B5CF6', content: 'Your learning follows a natural progression: Data (learn the facts) → Information (understand what they mean) → Knowledge (apply to problems) → Wisdom (make judgments and create). Early lessons help you remember and understand. Later lessons challenge you to analyze, evaluate, and create your own solutions.', deeper: 'Your DIKW dashboard shows where you are on this journey. As you master Data and Information, you unlock harder activities at the Knowledge and Wisdom levels. The platform tracks your progress through this pyramid — not just your scores, but HOW you think.\n\nWhat this means for you: You\'re not just learning facts. You\'re building the ability to think independently — which is what matters in real life.' },
  { icon: '🎯', title: 'Designed for Your Level', color: '#0891B2', content: 'LEAP adapts to your class level automatically. If you\'re in Class 3, lessons use simple language, stories, and fun examples. If you\'re in Class 11, you get real-world case studies, data analysis, and debate-style learning. The same platform works for everyone — but the experience is personalized for your age and level.', deeper: 'For younger students: Short lessons (30 min), picture-based questions, fill-in-the-blank, and matching exercises. Stories and rhymes to make learning fun.\n\nFor older students: Longer sessions (45-50 min), analytical questions, essay prompts, real-world data, and critical thinking challenges.\n\nWhat this means for you: The platform speaks your language — whether you\'re 8 or 17.' },
  { icon: '💬', title: 'Ask the Lesson Assistant', color: '#B45309', content: 'Every lesson page has a chatbot (the blue bubble in the bottom-right corner). Ask it anything about the lesson — "Explain the key idea", "Give me an example", "What does this word mean?" — and it answers based on what you\'re learning.', deeper: 'The chatbot only answers from the lesson content, so you won\'t get off-topic responses. It\'s like having a personal tutor available anytime you\'re studying.\n\nWhat this means for you: Never get stuck on a concept — help is always one click away.' },
];

const ADMIN_STEPS: Step[] = [
  { icon: '🏫', title: 'School-Wide Intelligence', color: '#1B3A6B', content: 'As principal, LEAP gives you a bird\'s-eye view of every course, every teacher, and every student in your school. See which classes are thriving and which need attention — all from one dashboard.', deeper: 'The admin dashboard shows: total teachers, total courses, total students, overall school mastery, at-risk student count, and session completion rates. You can drill into any teacher\'s courses to see their analytics.\n\nWhat this means for you: Data-driven school management without micromanaging teachers.' },
  { icon: '📊', title: 'Teacher Performance Overview', color: '#2E75B6', content: 'See how each teacher\'s classes are performing. Compare mastery rates, session completion, quiz scores, and student engagement across subjects and class levels.', deeper: 'The teacher view shows: courses taught, average mastery across courses, at-risk student count, and whether they\'re using the platform actively. You can identify teachers who might need training or support.\n\nWhat this means for you: Support your teachers with evidence, not guesswork.' },
  { icon: '📈', title: 'Student Outcome Tracking', color: '#16A34A', content: 'Track student mastery across all courses and class levels. Identify at-risk students before they fall behind. See Bloom\'s Taxonomy distribution — are students just memorizing, or actually understanding and applying?', deeper: 'The student heatmap shows every student\'s mastery across every gate in every course. Students below 60% are automatically flagged. You can see dependency risks — where weakness in one subject cascades into another.\n\nWhat this means for you: Early intervention based on real data, not end-of-year exam surprises.' },
  { icon: '🗓️', title: 'Timetable & Session Management', color: '#7C3AED', content: 'View the school-wide timetable. See which sessions have been completed, which are in progress, and which are upcoming. Track session delivery across all classes.', deeper: 'The timetable integrates with course analytics — you can see not just when a session was held, but how students performed in that session\'s quiz.\n\nWhat this means for you: Operational visibility into daily teaching delivery.' },
  { icon: '🧠', title: 'DIKW Framework — From Facts to Wisdom', color: '#8B5CF6', content: 'Every course on LEAP follows the DIKW progression: Data → Information → Knowledge → Wisdom. The AI automatically structures lessons so early sessions cover facts and definitions, mid sessions build application skills, and late sessions develop judgment and original thinking. Teachers see where each student sits on this pyramid in real-time.', deeper: 'The DIKW Analytics dashboard shows you school-wide patterns:\n- What % of classes are still at Data level (memorizing) vs Knowledge level (applying) vs Wisdom level (thinking independently)?\n- Which teachers are successfully moving students up the pyramid?\n- Which subjects need more higher-order activities?\n\nThis aligns with the DIKW × Bloom\'s Taxonomy framework: AI handles Data and Information (bottom of pyramid). Teachers focus class time on Knowledge and Wisdom (top) — where human guidance matters most.\n\nWhat this means for you: You can measure not just how much students know, but how deeply they think. That\'s the real output of education.' },
  { icon: '🎯', title: 'One Platform, Every Class Level', color: '#0891B2', content: 'LEAP works across your entire school — from Class 1 to Class 12. The AI automatically adapts lesson plans, teaching scripts, quizzes, and analytics based on each class level. A Class 3 English course gets story-based hooks and simple MCQs. A Class 11 Economics course gets case-study debates and analytical essays. Same platform, right pedagogy.', deeper: 'Three pedagogy tiers activate automatically:\n\nPrimary (Class 1-5): 30-min sessions, simple language, story-based teaching, Bloom ceiling at Apply, 3-option MCQs, fill-in-the-blank.\n\nMiddle (Class 6-8): 40-min sessions, discovery-oriented, real-world problems, Bloom up to Analyze, graduated difficulty.\n\nSenior (Class 9-12): 45-50 min sessions, Socratic debate, case studies, full Bloom spectrum, essay questions, real Indian data.\n\nThis means you can adopt LEAP for the entire school with one deployment. Teachers just set the class level when creating a course — everything else adapts automatically.\n\nWhat this means for you: A single platform investment that scales from primary to senior secondary. No separate tools for different age groups.' },
  { icon: '🤖', title: 'AI-Powered Insights', color: '#B45309', content: 'The AI generates actionable suggestions for each course: remediation recommendations, pace changes, peer teaching opportunities, and content adjustments. As principal, you see the aggregate picture.', deeper: 'AI suggestions are per-course, but you can review them school-wide to identify patterns: "3 courses have struggling students in math foundations" might suggest a school-wide math intervention.\n\nWhat this means for you: Strategic insights that drive school-wide improvement.' },
  { icon: '🔒', title: 'Privacy & Access Control', color: '#374151', content: 'Teachers see only their own courses. Students see only their enrolled courses. As admin, you see everything in your school — but data never leaks across schools. Enterprise-grade security with Row-Level Security on every table.', deeper: 'Multi-tenant architecture ensures complete school isolation. Teacher data, student data, and analytics are all scoped to your school.\n\nWhat this means for you: Deploy with confidence — data privacy is built into the architecture.' },
];

export function PlatformGuidePage() {
  const { profile } = useAuth();
  const isCollege = profile?.school === 'Horizon University College' || profile?.email?.includes('college') || profile?.email?.includes('university') || profile?.email?.includes('hu.ac.ae');
  const role = profile?.role || 'teacher';
  const STEPS = role === 'student' ? STUDENT_STEPS : role === 'admin' ? ADMIN_STEPS : isCollege ? COLLEGE_STEPS : SCHOOL_STEPS;

  const [currentStep, setCurrentStep] = useState(0);
  const [showDeeper, setShowDeeper] = useState(false);
  const step = STEPS[currentStep];

  return (
    <div className="max-w-4xl mx-auto">
      {/* Header */}
      <div className="flex items-center gap-4 mb-6">
        <img src="/ikigai-logo.jpeg" alt="LEAP" className="h-10 w-auto" />
        {!isCollege && <><div className="w-px h-8 bg-gray-200" /><img src="/lmgc-logo.jpeg" alt="LMGC" className="h-12 w-auto" /></>}
        <div className="ml-2">
          <h1 className="text-xl font-black" style={{ color: isCollege ? '#7C3AED' : '#1B3A6B' }}>Platform Guide</h1>
          <p className="text-[11px] text-gray-400">{role === 'student' ? 'How LEAP helps you learn better' : role === 'admin' ? 'How LEAP empowers your school' : isCollege ? 'How LEAP empowers your multi-course teaching' : 'How LEAP empowers your teaching'}</p>
        </div>
      </div>

      {/* Step navigation pills */}
      <div className="flex gap-1.5 mb-6 flex-wrap">
        {STEPS.map((s, i) => (
          <button key={i} onClick={() => { setCurrentStep(i); setShowDeeper(false); }}
            className={`flex items-center gap-1.5 px-3 py-2 rounded-xl text-[12px] font-bold transition-all ${i === currentStep ? 'text-white shadow-card' : 'text-gray-500 bg-gray-50 hover:bg-gray-100'}`}
            style={i === currentStep ? { background: s.color } : {}}>
            <span>{s.icon}</span><span className="hidden md:inline">{i + 1}</span>
          </button>
        ))}
      </div>

      {/* Progress bar */}
      <div className="flex gap-1 mb-6">
        {STEPS.map((s, i) => <div key={i} className="flex-1 h-1 rounded-full transition-all" style={{ background: i <= currentStep ? s.color : '#E5E7EB' }} />)}
      </div>

      {/* Content Card */}
      <div className="card p-0 overflow-hidden fade-in" key={currentStep}>
        <div className="p-6" style={{ background: `${step.color}10` }}>
          <div className="flex items-center gap-3 mb-3">
            <span className="text-3xl">{step.icon}</span>
            <div>
              <p className="text-[10px] font-bold text-gray-400 uppercase">Step {currentStep + 1} of {STEPS.length}</p>
              <h2 className="text-lg font-black" style={{ color: step.color }}>{step.title}</h2>
            </div>
          </div>
          <p className="text-sm text-gray-700 leading-relaxed">{step.content}</p>
        </div>

        <div className="p-6 border-t border-gray-100">
          <button onClick={() => setShowDeeper(!showDeeper)} className="text-[12px] font-bold flex items-center gap-1.5 transition-colors" style={{ color: step.color }}>
            <span className="transition-transform" style={{ transform: showDeeper ? 'rotate(180deg)' : '' }}>{'\u25BC'}</span> Going Deeper
          </button>
          {showDeeper && (
            <div className="mt-3 animate-slide-down">
              {step.deeper.split('\n\n').map((para, i) => (
                <p key={i} className={`text-sm leading-relaxed mb-3 ${para.startsWith('What this means') ? 'font-medium text-gray-800 p-3 rounded-xl' : 'text-gray-600'}`}
                  style={para.startsWith('What this means') ? { background: `${step.color}08`, border: `1px solid ${step.color}20` } : {}}>{para}</p>
              ))}
            </div>
          )}
        </div>

        <div className="px-6 py-4 bg-gray-50 flex items-center justify-between">
          <button onClick={() => { setCurrentStep(Math.max(0, currentStep - 1)); setShowDeeper(false); }} disabled={currentStep === 0} className="btn-secondary text-[12px] disabled:opacity-30">&larr; Previous</button>
          <span className="text-[11px] text-gray-400">{currentStep + 1} / {STEPS.length}</span>
          {currentStep === STEPS.length - 1 ? (
            <Link to={role === 'student' ? '/student' : role === 'admin' ? '/admin' : '/teacher'} className="btn-primary text-[12px]">Go to Dashboard &rarr;</Link>
          ) : (
            <button onClick={() => { setCurrentStep(currentStep + 1); setShowDeeper(false); }} className="btn-primary text-[12px]">Next &rarr;</button>
          )}
        </div>
      </div>

      {/* Quick Jump Grid */}
      <div className={`grid gap-3 mt-6 ${STEPS.length <= 8 ? 'grid-cols-4' : 'grid-cols-5'}`}>
        {STEPS.map((s, i) => (
          <button key={i} onClick={() => { setCurrentStep(i); setShowDeeper(false); window.scrollTo({ top: 0, behavior: 'smooth' }); }}
            className={`card-interactive p-3 text-left ${i === currentStep ? 'ring-2' : ''}`} style={i === currentStep ? { borderColor: s.color } : {}}>
            <div className="flex items-center gap-2 mb-1"><span className="text-lg">{s.icon}</span><span className="text-[10px] font-bold text-gray-400">Step {i + 1}</span></div>
            <p className="text-[11px] font-semibold text-gray-700 leading-tight">{s.title}</p>
          </button>
        ))}
      </div>
    </div>
  );
}
